# Docker compose for an INSECURE development environment OUTSIDE of production

services:
  database:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=administrator
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - "rdb:/var/lib/postgresql/data"


  objectdb:
    image: "quay.io/minio/minio:latest"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=administrator
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001" --address ":9000"
    volumes:
      - "objectdb:/data"

  createbuckets:
    image: minio/mc
    depends_on:
      - objectdb
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      /usr/bin/mc config host add myminio http://objectdb:9000 admin administrator;
      /usr/bin/mc mb myminio/objects;
      /usr/bin/mc policy download myminio/objects;
      exit 0;
      "
    restart: no

volumes:
  rdb: {}
  objectdb: {}