// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v4.25.3
// source: protobufs/apiserver.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceSelectorType int32

const (
	ServiceSelectorType_SERVICE_SELECTOR_TYPE_NONE ServiceSelectorType = 0
	ServiceSelectorType_SERVICE_SELECTOR_TYPE_POD  ServiceSelectorType = 1
)

// Enum value maps for ServiceSelectorType.
var (
	ServiceSelectorType_name = map[int32]string{
		0: "SERVICE_SELECTOR_TYPE_NONE",
		1: "SERVICE_SELECTOR_TYPE_POD",
	}
	ServiceSelectorType_value = map[string]int32{
		"SERVICE_SELECTOR_TYPE_NONE": 0,
		"SERVICE_SELECTOR_TYPE_POD":  1,
	}
)

func (x ServiceSelectorType) Enum() *ServiceSelectorType {
	p := new(ServiceSelectorType)
	*p = x
	return p
}

func (x ServiceSelectorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceSelectorType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobufs_apiserver_proto_enumTypes[0].Descriptor()
}

func (ServiceSelectorType) Type() protoreflect.EnumType {
	return &file_protobufs_apiserver_proto_enumTypes[0]
}

func (x ServiceSelectorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceSelectorType.Descriptor instead.
func (ServiceSelectorType) EnumDescriptor() ([]byte, []int) {
	return file_protobufs_apiserver_proto_rawDescGZIP(), []int{0}
}

type IngressProtocol int32

const (
	IngressProtocol_TCP IngressProtocol = 0
	IngressProtocol_UDP IngressProtocol = 1
)

// Enum value maps for IngressProtocol.
var (
	IngressProtocol_name = map[int32]string{
		0: "TCP",
		1: "UDP",
	}
	IngressProtocol_value = map[string]int32{
		"TCP": 0,
		"UDP": 1,
	}
)

func (x IngressProtocol) Enum() *IngressProtocol {
	p := new(IngressProtocol)
	*p = x
	return p
}

func (x IngressProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IngressProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_protobufs_apiserver_proto_enumTypes[1].Descriptor()
}

func (IngressProtocol) Type() protoreflect.EnumType {
	return &file_protobufs_apiserver_proto_enumTypes[1]
}

func (x IngressProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IngressProtocol.Descriptor instead.
func (IngressProtocol) EnumDescriptor() ([]byte, []int) {
	return file_protobufs_apiserver_proto_rawDescGZIP(), []int{1}
}

type Void struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Void) Reset() {
	*x = Void{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_apiserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_apiserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_protobufs_apiserver_proto_rawDescGZIP(), []int{0}
}

type ApiVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Major      int32  `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor      int32  `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	Patch      int32  `protobuf:"varint,3,opt,name=patch,proto3" json:"patch,omitempty"`
	Api        int32  `protobuf:"varint,4,opt,name=api,proto3" json:"api,omitempty"`
	Kubernetes string `protobuf:"bytes,5,opt,name=kubernetes,proto3" json:"kubernetes,omitempty"`
}

func (x *ApiVersion) Reset() {
	*x = ApiVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_apiserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiVersion) ProtoMessage() {}

func (x *ApiVersion) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_apiserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiVersion.ProtoReflect.Descriptor instead.
func (*ApiVersion) Descriptor() ([]byte, []int) {
	return file_protobufs_apiserver_proto_rawDescGZIP(), []int{1}
}

func (x *ApiVersion) GetMajor() int32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *ApiVersion) GetMinor() int32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *ApiVersion) GetPatch() int32 {
	if x != nil {
		return x.Patch
	}
	return 0
}

func (x *ApiVersion) GetApi() int32 {
	if x != nil {
		return x.Api
	}
	return 0
}

func (x *ApiVersion) GetKubernetes() string {
	if x != nil {
		return x.Kubernetes
	}
	return ""
}

type NamespaceCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RamLimit int64  `protobuf:"varint,2,opt,name=ramLimit,proto3" json:"ramLimit,omitempty"`
}

func (x *NamespaceCreateRequest) Reset() {
	*x = NamespaceCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_apiserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamespaceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceCreateRequest) ProtoMessage() {}

func (x *NamespaceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_apiserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceCreateRequest.ProtoReflect.Descriptor instead.
func (*NamespaceCreateRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_apiserver_proto_rawDescGZIP(), []int{2}
}

func (x *NamespaceCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamespaceCreateRequest) GetRamLimit() int64 {
	if x != nil {
		return x.RamLimit
	}
	return 0
}

type NamespaceDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *NamespaceDeleteRequest) Reset() {
	*x = NamespaceDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_apiserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamespaceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceDeleteRequest) ProtoMessage() {}

func (x *NamespaceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_apiserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceDeleteRequest.ProtoReflect.Descriptor instead.
func (*NamespaceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_apiserver_proto_rawDescGZIP(), []int{3}
}

func (x *NamespaceDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Namespace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RamLimit int64  `protobuf:"varint,2,opt,name=ramLimit,proto3" json:"ramLimit,omitempty"`
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_apiserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_apiserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_protobufs_apiserver_proto_rawDescGZIP(), []int{4}
}

func (x *Namespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Namespace) GetRamLimit() int64 {
	if x != nil {
		return x.RamLimit
	}
	return 0
}

type Namespaces struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespaces []*Namespace `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
}

func (x *Namespaces) Reset() {
	*x = Namespaces{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_apiserver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Namespaces) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespaces) ProtoMessage() {}

func (x *Namespaces) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_apiserver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespaces.ProtoReflect.Descriptor instead.
func (*Namespaces) Descriptor() ([]byte, []int) {
	return file_protobufs_apiserver_proto_rawDescGZIP(), []int{5}
}

func (x *Namespaces) GetNamespaces() []*Namespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type ServiceFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *ServiceFilter) Reset() {
	*x = ServiceFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_apiserver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceFilter) ProtoMessage() {}

func (x *ServiceFilter) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_apiserver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceFilter.ProtoReflect.Descriptor instead.
func (*ServiceFilter) Descriptor() ([]byte, []int) {
	return file_protobufs_apiserver_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceFilter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceFilter) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ContainerConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image string            `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Port  int32             `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Ram   int64             `protobuf:"varint,3,opt,name=ram,proto3" json:"ram,omitempty"`
	Env   map[string]string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ContainerConfiguration) Reset() {
	*x = ContainerConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_apiserver_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerConfiguration) ProtoMessage() {}

func (x *ContainerConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_apiserver_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerConfiguration.ProtoReflect.Descriptor instead.
func (*ContainerConfiguration) Descriptor() ([]byte, []int) {
	return file_protobufs_apiserver_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerConfiguration) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerConfiguration) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ContainerConfiguration) GetRam() int64 {
	if x != nil {
		return x.Ram
	}
	return 0
}

func (x *ContainerConfiguration) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type PodCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string                  `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Container *ContainerConfiguration `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
}

func (x *PodCreateRequest) Reset() {
	*x = PodCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_apiserver_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodCreateRequest) ProtoMessage() {}

func (x *PodCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_apiserver_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodCreateRequest.ProtoReflect.Descriptor instead.
func (*PodCreateRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_apiserver_proto_rawDescGZIP(), []int{8}
}

func (x *PodCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodCreateRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodCreateRequest) GetContainer() *ContainerConfiguration {
	if x != nil {
		return x.Container
	}
	return nil
}

type PodDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *PodDeleteRequest) Reset() {
	*x = PodDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_apiserver_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodDeleteRequest) ProtoMessage() {}

func (x *PodDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_apiserver_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodDeleteRequest.ProtoReflect.Descriptor instead.
func (*PodDeleteRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_apiserver_proto_rawDescGZIP(), []int{9}
}

func (x *PodDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodDeleteRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type Pod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ContainerPort int32  `protobuf:"varint,3,opt,name=containerPort,proto3" json:"containerPort,omitempty"`
}

func (x *Pod) Reset() {
	*x = Pod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_apiserver_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_apiserver_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_protobufs_apiserver_proto_rawDescGZIP(), []int{10}
}

func (x *Pod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pod) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Pod) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

type ServiceSelector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type ServiceSelectorType `protobuf:"varint,1,opt,name=type,proto3,enum=prismcloud.ServiceSelectorType" json:"type,omitempty"`
	Name string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ServiceSelector) Reset() {
	*x = ServiceSelector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_apiserver_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceSelector) ProtoMessage() {}

func (x *ServiceSelector) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_apiserver_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceSelector.ProtoReflect.Descriptor instead.
func (*ServiceSelector) Descriptor() ([]byte, []int) {
	return file_protobufs_apiserver_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceSelector) GetType() ServiceSelectorType {
	if x != nil {
		return x.Type
	}
	return ServiceSelectorType_SERVICE_SELECTOR_TYPE_NONE
}

func (x *ServiceSelector) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LBIngressPortConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerPort int32           `protobuf:"varint,1,opt,name=containerPort,proto3" json:"containerPort,omitempty"`
	ServicePort   int32           `protobuf:"varint,2,opt,name=servicePort,proto3" json:"servicePort,omitempty"`
	Protocol      IngressProtocol `protobuf:"varint,3,opt,name=protocol,proto3,enum=prismcloud.IngressProtocol" json:"protocol,omitempty"`
}

func (x *LBIngressPortConfiguration) Reset() {
	*x = LBIngressPortConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_apiserver_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LBIngressPortConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LBIngressPortConfiguration) ProtoMessage() {}

func (x *LBIngressPortConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_apiserver_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LBIngressPortConfiguration.ProtoReflect.Descriptor instead.
func (*LBIngressPortConfiguration) Descriptor() ([]byte, []int) {
	return file_protobufs_apiserver_proto_rawDescGZIP(), []int{12}
}

func (x *LBIngressPortConfiguration) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *LBIngressPortConfiguration) GetServicePort() int32 {
	if x != nil {
		return x.ServicePort
	}
	return 0
}

func (x *LBIngressPortConfiguration) GetProtocol() IngressProtocol {
	if x != nil {
		return x.Protocol
	}
	return IngressProtocol_TCP
}

type LBIngressCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string                      `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Selector  *ServiceSelector            `protobuf:"bytes,3,opt,name=selector,proto3" json:"selector,omitempty"`
	Port      *LBIngressPortConfiguration `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *LBIngressCreateRequest) Reset() {
	*x = LBIngressCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_apiserver_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LBIngressCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LBIngressCreateRequest) ProtoMessage() {}

func (x *LBIngressCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_apiserver_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LBIngressCreateRequest.ProtoReflect.Descriptor instead.
func (*LBIngressCreateRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_apiserver_proto_rawDescGZIP(), []int{13}
}

func (x *LBIngressCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LBIngressCreateRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LBIngressCreateRequest) GetSelector() *ServiceSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *LBIngressCreateRequest) GetPort() *LBIngressPortConfiguration {
	if x != nil {
		return x.Port
	}
	return nil
}

type LBIngressDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *LBIngressDeleteRequest) Reset() {
	*x = LBIngressDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_apiserver_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LBIngressDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LBIngressDeleteRequest) ProtoMessage() {}

func (x *LBIngressDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_apiserver_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LBIngressDeleteRequest.ProtoReflect.Descriptor instead.
func (*LBIngressDeleteRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_apiserver_proto_rawDescGZIP(), []int{14}
}

func (x *LBIngressDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LBIngressDeleteRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type LBIngress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string          `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ContainerPort int32           `protobuf:"varint,4,opt,name=containerPort,proto3" json:"containerPort,omitempty"`
	ServicePort   int32           `protobuf:"varint,3,opt,name=servicePort,proto3" json:"servicePort,omitempty"`
	Protocol      IngressProtocol `protobuf:"varint,5,opt,name=protocol,proto3,enum=prismcloud.IngressProtocol" json:"protocol,omitempty"`
}

func (x *LBIngress) Reset() {
	*x = LBIngress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_apiserver_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LBIngress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LBIngress) ProtoMessage() {}

func (x *LBIngress) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_apiserver_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LBIngress.ProtoReflect.Descriptor instead.
func (*LBIngress) Descriptor() ([]byte, []int) {
	return file_protobufs_apiserver_proto_rawDescGZIP(), []int{15}
}

func (x *LBIngress) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LBIngress) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LBIngress) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *LBIngress) GetServicePort() int32 {
	if x != nil {
		return x.ServicePort
	}
	return 0
}

func (x *LBIngress) GetProtocol() IngressProtocol {
	if x != nil {
		return x.Protocol
	}
	return IngressProtocol_TCP
}

var File_protobufs_apiserver_proto protoreflect.FileDescriptor

var file_protobufs_apiserver_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72, 0x69,
	0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x22, 0x06, 0x0a, 0x04, 0x56, 0x6f, 0x69, 0x64, 0x22,
	0x80, 0x01, 0x0a, 0x0a, 0x41, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d,
	0x61, 0x6a, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x61, 0x74, 0x63, 0x68,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61,
	0x70, 0x69, 0x12, 0x1e, 0x0a, 0x0a, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74,
	0x65, 0x73, 0x22, 0x48, 0x0a, 0x16, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x61, 0x6d, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x72, 0x61, 0x6d, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x2c, 0x0a, 0x16,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3b, 0x0a, 0x09, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x61, 0x6d, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72,
	0x61, 0x6d, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x43, 0x0a, 0x0a, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x69, 0x73,
	0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x22, 0x41, 0x0a, 0x0d,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22,
	0xcb, 0x01, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x72, 0x61, 0x6d, 0x12, 0x3d, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x03, 0x65, 0x6e, 0x76, 0x1a, 0x36, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x86, 0x01,
	0x0a, 0x10, 0x50, 0x6f, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x22, 0x44, 0x0a, 0x10, 0x50, 0x6f, 0x64, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x5d, 0x0a, 0x03,
	0x50, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x5a, 0x0a, 0x0f, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x33,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x70,
	0x72, 0x69, 0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x9d, 0x01, 0x0a, 0x1a, 0x4c, 0x42, 0x49, 0x6e,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x37,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1b, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x49, 0x6e,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0xbf, 0x01, 0x0a, 0x16, 0x4c, 0x42, 0x49, 0x6e,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x3a, 0x0a,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72,
	0x69, 0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4c, 0x42, 0x49, 0x6e, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x50, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x4a, 0x0a, 0x16, 0x4c, 0x42, 0x49,
	0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0xbe, 0x01, 0x0a, 0x09, 0x4c, 0x42, 0x49, 0x6e, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x37, 0x0a,
	0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1b, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x49, 0x6e, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2a, 0x54, 0x0a, 0x13, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a,
	0x1a, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x53, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x4f,
	0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x1d, 0x0a,
	0x19, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x53, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x4f,
	0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x4f, 0x44, 0x10, 0x01, 0x2a, 0x23, 0x0a, 0x0f,
	0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12,
	0x07, 0x0a, 0x03, 0x54, 0x43, 0x50, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x44, 0x50, 0x10,
	0x01, 0x32, 0xa5, 0x05, 0x0a, 0x13, 0x50, 0x72, 0x69, 0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x41, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x07, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x41, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x39,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x12,
	0x10, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x56, 0x6f, 0x69,
	0x64, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x12, 0x4c, 0x0a, 0x0f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x22, 0x2e, 0x70,
	0x72, 0x69, 0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x69,
	0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10,
	0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x56, 0x6f, 0x69, 0x64,
	0x12, 0x3b, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x64, 0x12, 0x1c, 0x2e,
	0x70, 0x72, 0x69, 0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x50, 0x6f, 0x64, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x72,
	0x69, 0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x3b, 0x0a,
	0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x64, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x69,
	0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x50, 0x6f, 0x64, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x34, 0x0a, 0x06, 0x47, 0x65,
	0x74, 0x50, 0x6f, 0x64, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a,
	0x0f, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x50, 0x6f, 0x64,
	0x12, 0x4c, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x42, 0x49, 0x6e, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2e, 0x4c, 0x42, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4c, 0x42, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x47,
	0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x42, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4c,
	0x42, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x40, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4c, 0x42,
	0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x4c, 0x42, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x42, 0x1a, 0x5a, 0x18, 0x70, 0x72, 0x69,
	0x73, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobufs_apiserver_proto_rawDescOnce sync.Once
	file_protobufs_apiserver_proto_rawDescData = file_protobufs_apiserver_proto_rawDesc
)

func file_protobufs_apiserver_proto_rawDescGZIP() []byte {
	file_protobufs_apiserver_proto_rawDescOnce.Do(func() {
		file_protobufs_apiserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobufs_apiserver_proto_rawDescData)
	})
	return file_protobufs_apiserver_proto_rawDescData
}

var file_protobufs_apiserver_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protobufs_apiserver_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_protobufs_apiserver_proto_goTypes = []interface{}{
	(ServiceSelectorType)(0),           // 0: prismcloud.ServiceSelectorType
	(IngressProtocol)(0),               // 1: prismcloud.IngressProtocol
	(*Void)(nil),                       // 2: prismcloud.Void
	(*ApiVersion)(nil),                 // 3: prismcloud.ApiVersion
	(*NamespaceCreateRequest)(nil),     // 4: prismcloud.NamespaceCreateRequest
	(*NamespaceDeleteRequest)(nil),     // 5: prismcloud.NamespaceDeleteRequest
	(*Namespace)(nil),                  // 6: prismcloud.Namespace
	(*Namespaces)(nil),                 // 7: prismcloud.Namespaces
	(*ServiceFilter)(nil),              // 8: prismcloud.ServiceFilter
	(*ContainerConfiguration)(nil),     // 9: prismcloud.ContainerConfiguration
	(*PodCreateRequest)(nil),           // 10: prismcloud.PodCreateRequest
	(*PodDeleteRequest)(nil),           // 11: prismcloud.PodDeleteRequest
	(*Pod)(nil),                        // 12: prismcloud.Pod
	(*ServiceSelector)(nil),            // 13: prismcloud.ServiceSelector
	(*LBIngressPortConfiguration)(nil), // 14: prismcloud.LBIngressPortConfiguration
	(*LBIngressCreateRequest)(nil),     // 15: prismcloud.LBIngressCreateRequest
	(*LBIngressDeleteRequest)(nil),     // 16: prismcloud.LBIngressDeleteRequest
	(*LBIngress)(nil),                  // 17: prismcloud.LBIngress
	nil,                                // 18: prismcloud.ContainerConfiguration.EnvEntry
}
var file_protobufs_apiserver_proto_depIdxs = []int32{
	6,  // 0: prismcloud.Namespaces.namespaces:type_name -> prismcloud.Namespace
	18, // 1: prismcloud.ContainerConfiguration.env:type_name -> prismcloud.ContainerConfiguration.EnvEntry
	9,  // 2: prismcloud.PodCreateRequest.container:type_name -> prismcloud.ContainerConfiguration
	0,  // 3: prismcloud.ServiceSelector.type:type_name -> prismcloud.ServiceSelectorType
	1,  // 4: prismcloud.LBIngressPortConfiguration.protocol:type_name -> prismcloud.IngressProtocol
	13, // 5: prismcloud.LBIngressCreateRequest.selector:type_name -> prismcloud.ServiceSelector
	14, // 6: prismcloud.LBIngressCreateRequest.port:type_name -> prismcloud.LBIngressPortConfiguration
	1,  // 7: prismcloud.LBIngress.protocol:type_name -> prismcloud.IngressProtocol
	2,  // 8: prismcloud.PrismcloudApiserver.Version:input_type -> prismcloud.Void
	2,  // 9: prismcloud.PrismcloudApiserver.GetNamespaces:input_type -> prismcloud.Void
	4,  // 10: prismcloud.PrismcloudApiserver.CreateNamespace:input_type -> prismcloud.NamespaceCreateRequest
	5,  // 11: prismcloud.PrismcloudApiserver.DeleteNamespace:input_type -> prismcloud.NamespaceDeleteRequest
	10, // 12: prismcloud.PrismcloudApiserver.CreatePod:input_type -> prismcloud.PodCreateRequest
	11, // 13: prismcloud.PrismcloudApiserver.DeletePod:input_type -> prismcloud.PodDeleteRequest
	8,  // 14: prismcloud.PrismcloudApiserver.GetPod:input_type -> prismcloud.ServiceFilter
	15, // 15: prismcloud.PrismcloudApiserver.CreateLBIngress:input_type -> prismcloud.LBIngressCreateRequest
	16, // 16: prismcloud.PrismcloudApiserver.DeleteLBIngress:input_type -> prismcloud.LBIngressDeleteRequest
	8,  // 17: prismcloud.PrismcloudApiserver.GetLBIngress:input_type -> prismcloud.ServiceFilter
	3,  // 18: prismcloud.PrismcloudApiserver.Version:output_type -> prismcloud.ApiVersion
	7,  // 19: prismcloud.PrismcloudApiserver.GetNamespaces:output_type -> prismcloud.Namespaces
	6,  // 20: prismcloud.PrismcloudApiserver.CreateNamespace:output_type -> prismcloud.Namespace
	2,  // 21: prismcloud.PrismcloudApiserver.DeleteNamespace:output_type -> prismcloud.Void
	2,  // 22: prismcloud.PrismcloudApiserver.CreatePod:output_type -> prismcloud.Void
	2,  // 23: prismcloud.PrismcloudApiserver.DeletePod:output_type -> prismcloud.Void
	12, // 24: prismcloud.PrismcloudApiserver.GetPod:output_type -> prismcloud.Pod
	17, // 25: prismcloud.PrismcloudApiserver.CreateLBIngress:output_type -> prismcloud.LBIngress
	2,  // 26: prismcloud.PrismcloudApiserver.DeleteLBIngress:output_type -> prismcloud.Void
	17, // 27: prismcloud.PrismcloudApiserver.GetLBIngress:output_type -> prismcloud.LBIngress
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_protobufs_apiserver_proto_init() }
func file_protobufs_apiserver_proto_init() {
	if File_protobufs_apiserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobufs_apiserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Void); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_apiserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_apiserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamespaceCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_apiserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamespaceDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_apiserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Namespace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_apiserver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Namespaces); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_apiserver_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_apiserver_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_apiserver_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_apiserver_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_apiserver_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_apiserver_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceSelector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_apiserver_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LBIngressPortConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_apiserver_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LBIngressCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_apiserver_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LBIngressDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_apiserver_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LBIngress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobufs_apiserver_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobufs_apiserver_proto_goTypes,
		DependencyIndexes: file_protobufs_apiserver_proto_depIdxs,
		EnumInfos:         file_protobufs_apiserver_proto_enumTypes,
		MessageInfos:      file_protobufs_apiserver_proto_msgTypes,
	}.Build()
	File_protobufs_apiserver_proto = out.File
	file_protobufs_apiserver_proto_rawDesc = nil
	file_protobufs_apiserver_proto_goTypes = nil
	file_protobufs_apiserver_proto_depIdxs = nil
}
