#
#
#type Config struct {
#MaxPlayers                  int    `toml:"max-players"`
#ViewDistance                int32  `toml:"view-distance"`
#ListenAddress               string `toml:"listen-address"`
#MessageOfTheDay             string `toml:"motd"`
#NetworkCompressionThreshold int    `toml:"network-compression-threshold"`
#OnlineMode                  bool   `toml:"online-mode"`
#LevelName                   string `toml:"level-name"`
#EnforceSecureProfile        bool   `toml:"enforce-secure-profile"`

#ChunkLoadingLimiter       Limiter `toml:"chunk-loading-limiter"`
#PlayerChunkLoadingLimiter Limiter `toml:"player-chunk-loading-limiter"`
#}

#type Limiter struct {
#Every duration `toml:"every"`
#N     int
#}
#

max-players = 10
view-distance = 10
listen-address = "0.0.0.0:25565"
motd = "A Minecraft Server"
network-compression-threshold = 256
online-mode = false
level-name = "world"
enforce-secure-profile = true

[chunk-loading-limiter]
every = "1s"
n = 10000

[player-chunk-loading-limiter]
every = "1s"
n = 10000